### ISSUE TITLE
Extra pubkey validation code is needed?

### ISSUE THREAD

**Issue by yshurik** [bpeel/notbit#32]
Caught one fault with very long-time notbit running:

Assertion failed: int_result (ntb-ecc.c: decode_pub_key: 466)

Is there possibility not to crash on such malformed pubkeys? Some extra check?

**Comment by bpeel** [comment]
Thanks for finding this. I’ve pushed a patch to make it check the return value instead of asserting. It looks like the call to `EC_POINT_set_affine_coordinates_GFp` could fail if a peer sends a coordinate that is not on the curve so I guess it should be checking the invalid data instead of asserting. I’m not sure why I made it like that in first place.
